name: Node.js CI
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org'
    - name: Install npm dependencies
      run: npm ci
    - name: Perform style check
      run: npm run lint
    - name: Publish tag to npm
      if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      run: npm publish
